version: "3"
services:
  relay:
    build: .
    volumes:
      - ./meson/librocksdb.a:/app/meson/librocksdb.a
    #restart: always
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8080:8080
